spring:
  application:
    name: hhplus
  profiles:
    active: test
  datasource:
#    name: HangHaePlusDataSource
    url: jdbc:mysql://localhost:3306/ecommerce?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: coffee
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 3
      connection-timeout: 10000
      max-lifetime: 60000
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.timezone.default_storage: NORMALIZE_UTC
      hibernate.jdbc.time_zone: UTC

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: kr.hhplus.be.server.*.model
  configuration:
    map-underscore-to-camel-case: true

---
spring.config.activate.on-profile: local, test
